In [8]:
#pip install numpy

492.76s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np

In [14]:
array1 = np.array([1, 2, 3])
print('array1 type : ',type(array1))
print('array1 array 형태 : ',array1.shape)
print(array1, array1.dtype)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type : ',type(array2))
print('array2 array 형태 : ',array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type : ',type(array3))
print('array3 array 형태 : ',array3.shape)



array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
[1 2 3] int64
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


In [18]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1., 2.]
array3 = np.array(list3)
print(array3, array3.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)



['1' '2' 'test'] <U21
[1. 2.] float64
[1 2 3] int32


In [20]:
sequence_array = np.arange(10)
print(sequence_array)
print(type(sequence_array))
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64 (10,)


In [21]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,3), dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32 (3, 3)


In [23]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d.tolist())

array5 = array3d.reshape(-1, 1)
print(array5.tolist())

array6 = array1.reshape(-1,1)
print(array6.tolist())

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


In [27]:
array1 = np.arange(start=1, stop=10)
print(array1)
value = array1[2]
print(value)

print('맨 뒤의 값:', array1[-1], '맨 뒤에 있는 두번째 값', array1[-2])

[1 2 3 4 5 6 7 8 9]
3
맨 뒤의 값: 9 맨 뒤에 있는 두번째 값 8


In [28]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array1[0:3]
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


팬시인덱스

In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
array3 = array2d[[0,1],2]
print(array3)

array4 = array2d[[0,1], 0:2]
print(array4)

array5 = array2d[[0,1]]
print(array5)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


불리언인덱싱

In [39]:
array3 = array1d[array1d > 5]
print(array1d > 5)
print(array3)

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print(array3)

[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


sort(), argsort() 는 개인이 해보기

행렬 내적
전치 행렬